version: '3.9'
services:
  database:
    image: mongo:4.1.13
    networks:
      - backend_network
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile 
    networks:
      - backend_network
    ports:
      - 3000:3000
    depends_on:
      - database
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/live || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  mongo_data:

networks:
  backend_network:
    driver: bridge